language: cpp
sudo: required

services:
  - docker

git:
  depth: 1

matrix:
  include:
    # OS X El Capitan 10.11, mesos-format
    - env: TOOL=mesos-format
      compiler: clang
      os: osx
      osx_image: xcode7.3
    # OS X El Capitan 10.11, mesos-tidy
    - env: TOOL=mesos-tidy
      compiler: clang
      os: osx
      osx_image: xcode7.3
    # OS X Sierra 10.12, mesos-format
    - env: TOOL=mesos-format
      compiler: clang
      os: osx
      osx_image: xcode8.3
    # OS X Sierra 10.12, mesos-tidy
    - env: TOOL=mesos-tidy
      compiler: clang
      os: osx
      osx_image: xcode8.3
    # Ubuntu 14.04, mesos-format
    - env: TOOL=mesos-format
      compiler: gcc
      os: linux
      dist: trusty
    # Ubuntu 14.04, mesos-tidy
    - env: TOOL=mesos-tidy
      compiler: gcc
      os: linux
      dist: trusty

script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew tap mesos/llvm
      brew install --verbose --build-bottle "${TOOL}"
      brew bottle "${TOOL}"
    elif [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker build -t "${TOOL}" --file "${TOOL}".dockerfile .
      docker run --rm -v "$(pwd)":/install:Z "${TOOL}"
    fi
  - ls -R

notifications:
  email: false
