language: cpp

git:
  depth: 1

matrix:
  include:
    # OS X El Capitan 10.11, mesos-format
    - env: TOOL=mesos-format
      compiler: clang
      os: osx
      osx_image: xcode7.3
    # OS X El Capitan 10.11, mesos-tidy
    - env: TOOL=mesos-tidy
      compiler: clang
      os: osx
      osx_image: xcode7.3
    # OS X Sierra 10.12, mesos-format
    - env: TOOL=mesos-format
      compiler: clang
      os: osx
      osx_image: xcode8.3
    # OS X Sierra 10.12, mesos-tidy
    - env: TOOL=mesos-tidy
      compiler: clang
      os: osx
      osx_image: xcode8.3

install:
  - brew update
  - brew tap mesos/llvm
  - brew install --verbose --build-bottle "${TOOL}"

script:
  - brew bottle "${TOOL}"

after_success:
  - ls -R

notifications:
  email: false
